name: Semantic Release (Release)

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.WORKFLOW_PUSHER_ID }}
          private-key: ${{ secrets.WORKFLOW_PUSHER_SECRET }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@v10.6.1
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          prerelease: false

      - name: Trigger sync-development workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          event-type: sync-development
